services:
  rust_bot:
    build: ./

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_INITDB_DATABASE: rust_bot
    ports:
      - 27017:27017
