services:
  rust_bot:
    build: ./
    networks:
      - redis_nw
  redis:
    image: redis:latest-alpine
    ports:
      - "6379:6379"
    networks:
      - redis_nw
    volumes:
      - ./redis-data/:/root/redis
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD="example"
      - REDIS_DATABASES=1

networks:
  redis_nw:
    driver: bridge
